# Generated by Django 4.2.18 on 2025-02-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_string', models.CharField(max_length=2000)),
                ('input', models.CharField(max_length=2000)),
                ('expected_output', models.CharField(max_length=2000)),
            ],
        ),
    ]
