# Generated by Django 4.2.18 on 2025-02-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='input',
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.CharField(max_length=2000)),
                ('expected_output', models.CharField(max_length=2000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='editor.questions')),
            ],
        ),
    ]
