# Generated by Django 4.2.18 on 2025-02-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_remove_questions_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('IO', 'I/O'), ('UNIT', 'Unit')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
