# Generated by Django 4.2.18 on 2025-02-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_questions_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_input',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
