# Generated by Django 4.2.18 on 2025-03-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_alter_testcase_test_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='instructor_code',
            field=models.CharField(max_length=20000, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='user_starter_code',
            field=models.CharField(max_length=20000, default=""),
            preserve_default=False,
        ),
    ]
