# Generated by Django 4.2.18 on 2025-03-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_testcase_instructor_code_testcase_user_starter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='instructor_code',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='user_starter_code',
        ),
    ]
