# Generated by Django 4.2.18 on 2025-03-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_remove_testcase_instructor_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='instructor_code',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='testcase',
            name='user_starter_code',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
