# Generated by Django 4.2.18 on 2025-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_testcase_instructor_code_testcase_user_starter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='instructor_code',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='user_starter_code',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
