# Generated by Django 4.2.18 on 2025-03-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_alter_testcase_instructor_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='instructor_code',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='user_starter_code',
        ),
        migrations.AddField(
            model_name='questions',
            name='instructor_code',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='questions',
            name='user_starter_code',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
