# Generated by Django 4.2.18 on 2025-04-22 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0013_participantprofile_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participantprofile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
