# Generated by Django 4.2.18 on 2025-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0014_alter_participantprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='control_assessment_done_and_ai_used',
            field=models.BooleanField(default=False),
        ),
    ]
