# Generated by Django 4.2.18 on 2025-09-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0015_participantprofile_control_assessment_done_and_ai_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantprofile',
            old_name='control_assessment_done_and_ai_used',
            new_name='both_control_code_assessments_done',
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='both_experimental_code_assessments_done',
            field=models.BooleanField(default=False),
        ),
    ]
