# Generated by Django 4.2.18 on 2025-09-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0016_rename_control_assessment_done_and_ai_used_participantprofile_both_control_code_assessments_done_and'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_C', models.PositiveIntegerField(default=130)),
                ('target_E', models.PositiveIntegerField(default=130)),
            ],
        ),
        migrations.CreateModel(
            name='RandomizationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.JSONField(default=list)),
                ('block_size', models.PositiveIntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='pre_assessment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='pre_assessment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='pre_assessment_response_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='pre_assessment_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='randomized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
