# Generated by Django 4.2.18 on 2025-09-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0017_enrollmentcap_randomizationblock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantprofile',
            old_name='both_control_code_assessments_done',
            new_name='both_ai_and_non_ai_portion_of_code_assessment_completed',
        ),
        migrations.RenameField(
            model_name='participantprofile',
            old_name='both_experimental_code_assessments_done',
            new_name='post_assessment_completed',
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='post_assessment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='post_assessment_response_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='post_assessment_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
