# Generated by Django 4.2.18 on 2025-09-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0018_rename_both_control_code_assessments_done_participantprofile_both_ai_and_non_ai_portion_of_code_asse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.IntegerField(blank=True, null=True)),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('event', models.CharField(choices=[('ai_tab_open', 'AI tab opened'), ('ai_prompt', 'AI prompt sent'), ('ai_reply', 'AI reply shown'), ('paste', 'Paste into editor'), ('vis_hide', 'Page hidden'), ('vis_show', 'Page visible')], max_length=32)),
                ('model_id', models.CharField(blank=True, max_length=64)),
                ('prompt_chars', models.IntegerField(blank=True, null=True)),
                ('reply_chars', models.IntegerField(blank=True, null=True)),
                ('paste_chars', models.IntegerField(blank=True, null=True)),
                ('prompt_hash', models.CharField(blank=True, max_length=64)),
                ('reply_hash', models.CharField(blank=True, max_length=64)),
                ('ua', models.TextField(blank=True)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'attempt_no', 'event'], name='editor_aite_user_id_31c466_idx'), models.Index(fields=['created_at'], name='editor_aite_created_d9f99c_idx')],
            },
        ),
    ]
