# Generated by Django 4.2.18 on 2025-09-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0019_aitelemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='post_assessment_started',
            field=models.BooleanField(default=False),
        ),
    ]
