# Generated by Django 4.2.18 on 2025-11-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0020_participantprofile_post_assessment_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitelemetry',
            name='prompt_chars',
        ),
        migrations.AddField(
            model_name='aitelemetry',
            name='prompt',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
