# Generated by Django 4.2.18 on 2025-11-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0021_remove_aitelemetry_prompt_chars_aitelemetry_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitelemetry',
            name='client_ts',
        ),
        migrations.RemoveField(
            model_name='aitelemetry',
            name='paste_chars',
        ),
        migrations.RemoveField(
            model_name='aitelemetry',
            name='question_id',
        ),
    ]
