# Generated by Django 4.2.18 on 2025-11-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0022_remove_aitelemetry_client_ts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitelemetry',
            name='prompt_hash',
        ),
        migrations.RemoveField(
            model_name='aitelemetry',
            name='reply_hash',
        ),
    ]
