# Generated by Django 4.2.18 on 2025-11-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0023_remove_aitelemetry_prompt_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitelemetry',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='aitelemetry',
            name='ua',
        ),
    ]
