# Generated by Django 4.2.18 on 2026-01-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0024_remove_aitelemetry_model_id_remove_aitelemetry_ua'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='harness_code',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
