# Generated by Django 4.2.18 on 2026-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0025_questions_harness_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
