# Generated by Django 4.2.18 on 2026-02-03 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0026_questions_question_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conversation_id', models.CharField(db_index=True, max_length=128)),
                ('turn_index', models.PositiveIntegerField()),
                ('mode', models.CharField(blank=True, max_length=16)),
                ('user_text', models.TextField()),
                ('assistant_text', models.TextField(blank=True)),
                ('history_turn_ids_sent', models.JSONField(blank=True, default=list)),
                ('history_window_size', models.PositiveSmallIntegerField(default=0)),
                ('openai_response_id', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'attempt_no', 'question', 'created_at'], name='editor_aica_user_id_a3e66f_idx'), models.Index(fields=['conversation_id', 'turn_index'], name='editor_aica_convers_0ab195_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aicall',
            constraint=models.UniqueConstraint(fields=('conversation_id', 'turn_index'), name='uniq_conversation_turn'),
        ),
    ]
