# Generated by Django 4.2.18 on 2026-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0027_aicall_aicall_uniq_conversation_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], db_index=True, default='M', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'attempt_no'), name='uniq_user_question_attempt'),
        ),
    ]
