# Generated by Django 4.2.18 on 2026-02-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0028_questions_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='second_attempt_incorrect',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
