# Generated by Django 4.2.18 on 2026-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0029_participantprofile_second_attempt_incorrect'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='uniq_user_question_attempt',
        ),
        migrations.RemoveField(
            model_name='participantprofile',
            name='second_attempt_incorrect',
        ),
        migrations.AddField(
            model_name='submission',
            name='time_spent_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MED', 'Medium'), ('HARD', 'Hard')], db_index=True, default='EASY', max_length=8),
        ),
    ]
