# Generated by Django 4.2.18 on 2026-02-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0030_remove_submission_uniq_user_question_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='control_all_correct',
            field=models.BooleanField(default=False),
        ),
    ]
