# Generated by Django 4.2.18 on 2026-02-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0031_participantprofile_control_all_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='raffle_page_completed',
            field=models.BooleanField(default=False),
        ),
    ]
