# Generated by Django 4.2.18 on 2026-02-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0032_participantprofile_raffle_page_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='raffle_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='raffle_response_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='raffle_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
