# Generated by Django 4.2.18 on 2026-02-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0033_participantprofile_raffle_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='compile_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_testcase_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed_test_cases',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='runtime_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_test_cases',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'attempt_no'), name='uniq_submission_user_question_attempt'),
        ),
    ]
