# Generated by Django 4.2.18 on 2026-02-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0034_submission_code_submission_compile_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='exp_all_wrong',
            field=models.BooleanField(default=False),
        ),
    ]
