# Generated by Django 4.2.18 on 2026-02-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0035_participantprofile_exp_all_wrong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicall',
            name='completion_tokens',
        ),
        migrations.RemoveField(
            model_name='aicall',
            name='latency_ms',
        ),
        migrations.RemoveField(
            model_name='aicall',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='aicall',
            name='prompt_tokens',
        ),
        migrations.RemoveField(
            model_name='aicall',
            name='total_tokens',
        ),
    ]
