# Generated by Django 4.2.18 on 2026-03-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0036_remove_aicall_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='group',
            field=models.CharField(choices=[('U', 'Unassigned'), ('C', 'Control'), ('E', 'Experimental')], db_index=True, default='U', max_length=1),
        ),
    ]
